# Generated by Django 4.1 on 2024-11-07 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_master',
            fields=[
                ('booking_master_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('booking_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur_app.booking_master')),
            ],
        ),
        migrations.AddField(
            model_name='booking_master',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur_app.user'),
        ),
        migrations.CreateModel(
            name='booking_child',
            fields=[
                ('booking_child_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('booking_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur_app.booking_master')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur_app.product')),
            ],
        ),
    ]
